/* eslint-disable */
// Generated by Wrangler by running `wrangler types env.d.ts --include-runtime false` (hash: 43748a5a32b699fe6d33cdfecb84d3bf)
declare namespace Cloudflare {
	interface Env {
		HOST_KEY: "change-me";
		PollRoom: DurableObjectNamespace<import("./src/server").PollRoom>;
		ASSETS: Fetcher;
	}
}
interface Env extends Cloudflare.Env {}
