/* eslint-disable */
// Generated by Wrangler by running `wrangler types env.d.ts --include-runtime false`
declare namespace Cloudflare {
	interface Env {
		HOST_KEY: "change-me";
		ADMIN_KEY: string;
		PollRoom: DurableObjectNamespace<import("./src/poll-room").PollRoom>;
		AdminRegistry: DurableObjectNamespace<import("./src/admin-registry").AdminRegistry>;
	}
}
interface Env extends Cloudflare.Env {}
