/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ScreenRouteImport } from './routes/screen'
import { Route as HostRouteImport } from './routes/host'
import { Route as IndexRouteImport } from './routes/index'
import { Route as RRoomIndexRouteImport } from './routes/r/$room/index'
import { Route as RRoomScreenRouteImport } from './routes/r/$room/screen'
import { Route as RRoomHostRouteImport } from './routes/r/$room/host'

const ScreenRoute = ScreenRouteImport.update({
  id: '/screen',
  path: '/screen',
  getParentRoute: () => rootRouteImport,
} as any)
const HostRoute = HostRouteImport.update({
  id: '/host',
  path: '/host',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const RRoomIndexRoute = RRoomIndexRouteImport.update({
  id: '/r/$room/',
  path: '/r/$room/',
  getParentRoute: () => rootRouteImport,
} as any)
const RRoomScreenRoute = RRoomScreenRouteImport.update({
  id: '/r/$room/screen',
  path: '/r/$room/screen',
  getParentRoute: () => rootRouteImport,
} as any)
const RRoomHostRoute = RRoomHostRouteImport.update({
  id: '/r/$room/host',
  path: '/r/$room/host',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/host': typeof HostRoute
  '/screen': typeof ScreenRoute
  '/r/$room/host': typeof RRoomHostRoute
  '/r/$room/screen': typeof RRoomScreenRoute
  '/r/$room/': typeof RRoomIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/host': typeof HostRoute
  '/screen': typeof ScreenRoute
  '/r/$room/host': typeof RRoomHostRoute
  '/r/$room/screen': typeof RRoomScreenRoute
  '/r/$room': typeof RRoomIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/host': typeof HostRoute
  '/screen': typeof ScreenRoute
  '/r/$room/host': typeof RRoomHostRoute
  '/r/$room/screen': typeof RRoomScreenRoute
  '/r/$room/': typeof RRoomIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/host'
    | '/screen'
    | '/r/$room/host'
    | '/r/$room/screen'
    | '/r/$room/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/host'
    | '/screen'
    | '/r/$room/host'
    | '/r/$room/screen'
    | '/r/$room'
  id:
    | '__root__'
    | '/'
    | '/host'
    | '/screen'
    | '/r/$room/host'
    | '/r/$room/screen'
    | '/r/$room/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  HostRoute: typeof HostRoute
  ScreenRoute: typeof ScreenRoute
  RRoomHostRoute: typeof RRoomHostRoute
  RRoomScreenRoute: typeof RRoomScreenRoute
  RRoomIndexRoute: typeof RRoomIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/screen': {
      id: '/screen'
      path: '/screen'
      fullPath: '/screen'
      preLoaderRoute: typeof ScreenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/host': {
      id: '/host'
      path: '/host'
      fullPath: '/host'
      preLoaderRoute: typeof HostRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/r/$room/': {
      id: '/r/$room/'
      path: '/r/$room'
      fullPath: '/r/$room/'
      preLoaderRoute: typeof RRoomIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/r/$room/screen': {
      id: '/r/$room/screen'
      path: '/r/$room/screen'
      fullPath: '/r/$room/screen'
      preLoaderRoute: typeof RRoomScreenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/r/$room/host': {
      id: '/r/$room/host'
      path: '/r/$room/host'
      fullPath: '/r/$room/host'
      preLoaderRoute: typeof RRoomHostRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  HostRoute: HostRoute,
  ScreenRoute: ScreenRoute,
  RRoomHostRoute: RRoomHostRoute,
  RRoomScreenRoute: RRoomScreenRoute,
  RRoomIndexRoute: RRoomIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
